### ISSUE TITLE
Be able to specify that a numeric value is within a certain range

### ISSUE THREAD

**Issue by gilescope** [NachoPal/parachains-integration-tests#35]
```
                      attribute:
                        type: XcmV2TraitsOutcome
                        isComplete: true
                        value: 4,000,000,000
```
Given that weights can be quite variable, it would be nice to be able to assert it's within a range. Maybe this could use rust range syntax: 1,000,000,000..4,000,000,000
