### ISSUE TITLE
Not possible to differentiate two events of one type 

### ISSUE THREAD

**Issue by muharem** [NachoPal/parachains-integration-tests#58]
When asserting events, its not possible to differentiate one event from another if they have same type and received in a row.

If I try to assert the first event from the example below, it will be asserted against second one
```
                - name: balances.Deposit
                  chain: *relay_chain
                  attributes:
                    - type: AccountId32
                      key: who
                      value: '5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY'
```

Example:
![Screenshot 2022-10-10 at 12 14 43](https://user-images.githubusercontent.com/6050188/194844415-a2393bee-6670-4bed-8ba7-f69a09bce004.png)
