### ISSUE TITLE
Support multiple asserts of same type

### ISSUE THREAD

**Issue by evilrobot-01** [NachoPal/parachains-integration-tests#76]
Currently one cannot have multiple asserts of the same type, as keys need to be unique. As an example:
```
              - asserts:
                  equal:
                    args: [ true, true ]
                  equal:
                    args: [ true, true ]
```
This results in `YAMLSemanticError: Map keys must be unique; "equal" is repeated`. 

Switching to using dashed notation works around this:
```
              - asserts:
                  - equal:
                      args: [ true, true ]
                  - equal:
                      args: [ true, true ]
```
But this then results in an issue when resolving the asserts, where the key name is its index (0,1 etc.) rather than the assert name (equal):

<img width="680" alt="image" src="https://user-images.githubusercontent.com/60948618/199672388-f1ee5bab-03c6-4fdc-9c0a-de3075acee2d.png">

A workaround is to separate them into additional assert sections, but having a single assert section would be ideal:

```
              - asserts:
                  equal:
                    args: [ true, true ]
              - asserts:
                  equal:
                    args: [ true, true ]
```
