### ISSUE TITLE
Support  thresholds for 2D weights in assertions.

### ISSUE THREAD

**Issue by ruseinov** [NachoPal/parachains-integration-tests#93]
Currently we aren't able to use thresholds, because they are designed to work with string/int values as opposed to a json object with two values. 

Here's an example of how that might look:

```
                    - name: polkadotXcm.Attempted
                      attributes:
                        - type: XcmV3TraitsOutcome
                          xcmOutcome: Complete
                          threshold: { refTime: [10, 10], proofSize: [20,20] }
                          value: { refTime: 100000, proofSize: 200 }
```
